### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by dten** [fschutt/printpdf#1]
Hello 👍  tried to get this running on Windows but it's mostly a no-go because of freetype. Any chance of using something friendlier 🤒

**Comment by fschutt** [comment]
I've tried using rusttype, the problem is the spacing of characters / kerning, rusttype does not have functions for getting the kerning between two characters. However, kerning is currently unused, anyway, so there might be a chance it works with rusttype.

I'm currently working on layering, will get back to this later. Yes, I'll switch to rusttype if possible.

**Comment by dten** [comment]
awesome 👍  thanks

**Comment by fschutt** [comment]
I have migrated to rusttype, however I will probaby add an option in the future to use freetype.

- rusttype is riddled with bugs
- rusttype does not allow OpenType fonts, FreeType does
- The maintainer of rusttype has left the project

So yeah, it's not looking too bright. I wouldn't set on a library just because it's written in Rust.
Right now the dependencies depend on my forks of rusttype and stb_truetype where I cleaned up the bugs. I have, however low hopes of these ever getting merged into the master branch, simply because the developer isn't active anymore.

I hope this solves the immediate issues.

**Comment by fschutt** [comment]
I am reverting this. `rusttype` does not work, it simply misplaces characters all over the place. You can use `printpdf 0.1` if you want to use `rusttype`, but for serious work, consider installing freetype.

**Comment by fschutt** [comment]
Alright. In version `0.1.1` and beyond I will use freetype. `rusttype` cannot get the unicode values of fonts reliably, has issues with getting font widths, can't embed postscript names, can't reliably get font metrics of unscaled fonts, etc. The author doesn't care about the library and it's not ready for production use. While `rusttype` would make this library easier to compile on windows, it makes the font placing features useless. If `rusttype` matures, it may be reconsidered, but for now `rusttype` is useless for this project.

On windows, you can tell can tell cargo where the `.a` (static library) file is: https://stackoverflow.com/questions/31769604/how-to-tell-rustc-through-cargo-where-to-find-my-dll-import-library

I'm closing this because this is not an issue with the library, but an issue with Windows.

**Comment by dten** [comment]
Thanks for trying! :)

**Comment by fschutt** [comment]
@dten This is probably not relevant to you anymore, but you can download binaries for FreeType here:

https://github.com/PistonDevelopers/binaries

and then follow the steps listed here:

https://github.com/PistonDevelopers/freetype-sys/blob/master/README.md

... to install freetype on windows. I used this successfully to cross-compile from Linux to Windows, so it should work. However you'd have to (currently) install the libraries yourself. I am thinking about writing a build script for this task (do the downloading and setting the link automatically).

**Comment by dten** [comment]
thanks for the info :)

**Comment by fschutt** [comment]
@dten Just FYI, the latest version of printpdf (0.2.4) now uses rusttype, due to various patches. It should build without problems on Windows.

**Comment by dten** [comment]
Sweet, will give it a spin
