### ISSUE TITLE
Support for very thin lines

### ISSUE THREAD

**Issue by emosenkis** [fschutt/printpdf#15]
I'd like to draw shapes with line thickness of ~0.08mm, but the line thickness setting accepts an i64, of which any value <= 0 seems to have the same result, which is still too thick. The unit for this setting isn't documented, so I'm not sure if it's supposed to be pt or mm (or neither, since 0 wouldn't be visible if it was a normal unit).

**Comment by fschutt** [comment]
The unit for outlines is point, unless otherwise noted, you can use the `mm_to_pt!()` macro to convert them.

But I think the issue is that it is converted to an `Integer` here:

https://github.com/fschutt/printpdf/blob/master/src/types/pdf_layer.rs#L251

However, I have to look in the PDF reference if the `w` operator accepts floats. "0" is a special line width, it will always draw the same thickness regardless of zoom factor. I think this should be `Real` but I have to look it up, thanks.

**Comment by fschutt** [comment]
PDF Reference 1.7, page 215:

> A line width of 0 denotes the thinnest line that can be rendered at device resolution:
1 device pixel wide. However, some devices cannot reproduce 1-pixel lines,
and on high-resolution devices, they are nearly invisible. Since the results of rendering
such zero-width lines are device-dependent, their use is not recommended.

Description of the line width on page 211, Table 4.3:

> line width - number - The thickness, in user space units, of paths to be stroked (see “Line
Width” on page 215). Initial value: 1.0. 

So it does accept a floating-point number. I've fixed this issue in version `0.2.1`.
