### ISSUE TITLE
Does set_word_spacing() work?

### ISSUE THREAD

**Issue by vlmutolo** [fschutt/printpdf#17]
The [documentation](https://github.com/fschutt/printpdf/blob/d21066760de9a3d0d93fca3201d80b8a9e7c706a/src/types/pdf_layer.rs#L338) clearly states that the `set_word_spacing` method (implemented for `pdf_layer`) is not operational. However, examples on the front page of the documentation show the method being used.

Is it safe to use `set_word_spacing`?

**Comment by fschutt** [comment]
@vlmutolo This is expressed rather poor in the documentation, sorry: It does work, but only if the text is drawn using a `BuiltinFont`, it does not work with an `ExternalFont`. 

The reason is this: PDF itself knows various encodings (Latin, Eastern, etc.), the default encoding being PDFDoc (which is similar to Ascii). Any text that is written with a `BuiltinFont` uses the PdfDoc encoding, but any text written with an `ExternalFont` uses Unicode (UTF-8, which gets converted to UTF-16, which PDF understands). Other PDF libraries have support for various encodings, but printpdf only writes UTF-16 / UTF-8. The benefit of that is that you generally don't have to worry about encoding, the drawback is that operations such as `set_word_spacing` don't work if you use Unicode.

`set_word_spacing` is a simple wrapper over the `Tw` PDF operation. The PDF reference says that the `Tw` operation only works if the text uses the PdfDoc encoding (TODO: source). 

See this example:

```rust
extern crate printpdf;

use printpdf::*;
use std::fs::File;
use std::io::{Cursor, BufWriter};

const EXTERNAL_FONT: &[u8] = include_bytes!("./RobotoMedium.ttf");

fn main() {
    let (doc, page1, layer1) = PdfDocument::new("PDF_Document_title", Mm(500.0), Mm(300.0), "Layer 1");
    let current_layer = doc.get_page(page1).get_layer(layer1);

    let mut font_reader = Cursor::new(EXTERNAL_FONT.as_ref());
    let font_external = doc.add_external_font(&mut font_reader).unwrap();
    let font_builtin = doc.add_builtin_font(BuiltinFont::TimesBoldItalic).unwrap();

    let text = "Lorem ipsum";

    // add text with the external font:
    current_layer.begin_text_section();
    current_layer.set_font(&font_external, 24);
    current_layer.set_text_cursor(Mm(10.0), Mm(100.0));
    current_layer.set_word_spacing(20);
    current_layer.write_text(text, &font_external);
    current_layer.end_text_section();

    // add text with the builtin font:  
    current_layer.begin_text_section();
    current_layer.set_font(&font_builtin, 24);
    current_layer.set_text_cursor(Mm(10.0), Mm(50.0));
    current_layer.set_word_spacing(20);
    current_layer.write_text(text, &font_builtin);
    current_layer.end_text_section();

    doc.save(&mut BufWriter::new(File::create("test_word_spacing.pdf").unwrap())).unwrap();
}
```

Result: 

![fonts](https://user-images.githubusercontent.com/12084016/41814648-0e41dee4-7754-11e8-842f-ca22d815309a.png)

Both fonts have the `set_word_spacing` enabled, but only the text drawn using the built-in Times New Roman font shows the effect of `set_word_spacing`.

Yes, printpdf could support various encodings, but getting that to work with fonts, etc. is a lot of work. Which is why I said: ok, let's just get UTF-8 to work for starters, custom encodings can come later - especially since you have to know what you're doing with custom encodings, otherwise you end up with ����� in your PDF. 

You can "emulate" the word spacing behaviour by using a [TextMatrix](https://docs.rs/printpdf/0.2.6/printpdf/types/plugins/graphics/ctm/enum.TextMatrix.html) and using [`set_text_matrix`](https://docs.rs/printpdf/0.2.6/printpdf/types/pdf_layer/struct.PdfLayerReference.html#method.set_text_matrix). This is also easier to control (with millimeter / points). I really only implemented this because I wanted a certain "completeness" in covering all PDF text operators, using `TextMatrix` is more flexible and it works with Unicode-encoded text.

**Comment by vlmutolo** [comment]
Thanks for this awesome (and surprisingly fast) response. The example you provided helps a lot. I will take a look at `TextMatrix`.

I'm closing the issue and I'll file a pull request with a small change in the documentation to reflect some of what you've written here. Thanks!

**Comment by fschutt** [comment]
Yeah, I'll need to go over the documentation, it isn't clear on this topic. Of course using a text matrix will increase the file size (i.e. if you put the whole Moby Dick text in there, you might see an increase of a few kilobytes, because the TextMatrix has to be set for each word individually (I think)). I should also add an example of using `TextMatrix`. Thanks for reporting this.
