### ISSUE TITLE
Running the shape example

### ISSUE THREAD

**Issue by tdejager** [fschutt/printpdf#19]
Hi!

Thanks for your work on creating this library. First off, the example that draws a shape needs this using
statement:
```rust
use std::iter::FromIterator;
```

Secondly, after copying the code verbatim running 1.28.0-nightly on OSX. This is the output. Is this correct as I assumed the seconds shape should be a triangle.

Thanks!
[test_working.pdf](https://github.com/fschutt/printpdf/files/2172570/test_working.pdf)

**Comment by fschutt** [comment]
1. It has that statement already:

https://github.com/fschutt/printpdf/blob/c7c1f8020eb9fbfdc834a35d524432d24e1cfc05/examples/graphics.rs#L6

And the Mac CI works, so I maybe you accidentally deleted that line?

2. It's a triangle, the top is just cut off because the page is set a bit too small:

![image](https://user-images.githubusercontent.com/12084016/42408960-66be7ed6-81d3-11e8-935a-60c8d7d8b3ce.png)

But yes, it's correct. I could set the page to be a bit larger, so this doesn't confuse anyone.

**Comment by fschutt** [comment]
Alright I'm closing this for now, I've adjusted the page size, so thanks for the report. If you still have issues running the example, feel free to reopen.

**Comment by tdejager** [comment]
Yes, you are right for closing this. I must have misread the example because it is there. Thanks!

Edit: I saw the example was updated But the Readme code has the old sizes still. :)
