### ISSUE TITLE
Private Indices module

### ISSUE THREAD

**Issue by jeroenvervaeke** [fschutt/printpdf#31]
I have a question regarding the design of the library. I'll start my question by describing what I'm trying to do.

I'm writing a small rust API which generates a PDF report. It's pretty straight forward, you throw data at it and it should spit out a PDF.
To do this created a simple struct `Report`, my goal is to be able to call `add_data` on my `Report` struct and that it automatically appends data and new pages (if needed) to the report.

This is the place where I get stuck with this library. To save the current page in my struct I need to be able to access `PdfPageIndex` from my application, which is not possible.

As far as I understood [indices.rs](https://github.com/fschutt/printpdf/blob/b362afa6caf735e566b52aba0d2b98dbdb0738c5/src/indices.rs#L1) are meant for internal use only.
However they're marked with `pub`. Also the public api to create a Pdf document returns a `PdfPageIndex`. In my opinion it's not logical to not export a type that's used in the public API.

I think a good solution would be to make `indices` public instead of [private](https://github.com/fschutt/printpdf/blob/b362afa6caf735e566b52aba0d2b98dbdb0738c5/src/lib.rs#L346). Another option would be to write some public wrapper structs that can be used in external applications. Otherwise we're restricted to write most of the code in one method, which isn't really good practice.

**Comment by fschutt** [comment]
Making the module private was an intentional decision - this library was written before `pub(crate)` was even a thing. So the only way you could "emulate" `pub(crate)` in the old way was to make the type public, but put it in a private module.

The goal was to prevent people from accidentally creating their own `PdfPageIndex` (remember, the only two visibility modifiers were "pub" and "not pub", so it had to be a [`PdfPageIndex(pub usize)`](https://github.com/fschutt/printpdf/blob/b362afa6caf735e566b52aba0d2b98dbdb0738c5/src/indices.rs#L7). Now it would be better to make the module public, as you said, but use a `PdfPageIndex(pub(crate) usize)` - so that only this library can create PdfPageIndexes, but external code (like yours) can still store them.

**Comment by jeroenvervaeke** [comment]
I wasn't aware of the `pub(crate)` feature. I'll create a PR.

**Comment by jeroenvervaeke** [comment]
See PR #32
