### ISSUE TITLE
Generated PDF are large - size 660KB

### ISSUE THREAD

**Issue by fbucek** [fschutt/printpdf#53]
No matter what I do, generated PDF files are large. 660KB in debug mode, 490KB in release mode on macOS. 

```
use printpdf::*;
use std::fs::File;
use std::io::BufWriter;

let (doc, page1, layer1) = PdfDocument::new("PDF_Document_title", Mm(247.0), Mm(210.0), "Layer 1");
let (page2, layer1) = doc.add_page(Mm(10.0), Mm(250.0),"Page 2, Layer 1");

doc.save(&mut BufWriter::new(File::create("test_working.pdf").unwrap())).unwrap();
```

This produces `test_working.pdf` with size of 660KB ( debug mode )

**Comment by fschutt** [comment]
Yes, because they have an ICC color profile embedded into it to comply with the PDF-X 1.4 standard for print production. If you don't need that, you can turn it off, see the [no_icc example](https://github.com/fschutt/printpdf/blob/a6fa46dad0f273cfd181eeebec7dc61e02559b4f/examples/no_icc.rs#L17-L19)

**Comment by fbucek** [comment]
Thank you. Now I am at 72KB which is good. Maybe some info to README.md would help others. I was looking for 'size' or similar and I could not find any info how to make it smaller.
