### ISSUE TITLE
More text formatting features in printpdf?

### ISSUE THREAD

**Issue by robinkrahl** [fschutt/printpdf#73]
I’m currently working on [`genpdf`](https://lib.rs/crates/genpdf), a document generator and layout engine built on top of `printpdf`.

In #2, you wrote:
>  I'd also really like to do layout in a seperate library, not in `printpdf` - this library should only contain what the PDF spec says and contain the "primitives" for building a PDF. Anything fancy, like tables, page breaks, etc. should be done in a seperate library.

I think this applies to most features in `genpdf`, but there are some `genpdf` features that might be useful for `printpdf`:
- <s>Measuring the width and height of strings</s> \*
- Kerning
- Transforming between the PDF coordinate system and the “logical” coordinate system (relative to the upper left corner)
- Views on a sub-area of a layer
- <s>Text alignment (left/center/right/justified)</s> \*
- A `TextSection` type to ensure matching `begin_text_section()` and `end_text_section()` calls

\* *Edit: I just saw that you already said that you don’t want to include this in `printpdf`*

Also, I plan to implement these features for `genpdf` that could be added to `printpdf` instead:
- Keeping track of the current settings (colors, spacing, line height, etc.) to avoid redundant operations

Are you interested in adding any of these features to `printpdf`?

**Comment by fschutt** [comment]
Short answer: no, long answer: There will probably be an API rewrite (maybe in a few years, I currently don't have that much time to spend on printpdf), where the API will look more like this:

```rust
let pdf = Pdf {
   resources: vec![
       Resource::Font{ data: load_font("Roboto.ttf")? },
   ]
   pages: vec![
        PdfPage {
            resources: vec![
                Resource::Image { data: load_image("foo.jpg")? },
            ]
            operators: vec![
                Operator::BeginTextSection(),
                Operator::UseFont(GlobalResource { index: 0 }),
                Operator::WriteText(font_size, glyphs, kerning, ... ),
                Operator::EndTextSection(),
                Operator::DrawImage(LocalResource { index: 0 }),
            ],
        }
    ]
};
```

... to get rid of all the `.borrow_mut()` and `.set_xxx()` calls.

Then you could (ideally) implement a `TextSection` like this:

```rust
operators: Vec::new()
   .append(
        TextSection {
             font: 0,
             text: "hello",
             kerning_engine: Box::new(HarfBuzzEngine::new()), // kerning / text shaping provider
         }.into_operators()
    )
    .append(Operator::DrawImage(LocalResource { index: 0 }))
],
```

This would allow for keeping the implementation of the text shaping engine outside of printpdf (currently it's tied to rusttype) and also allow for easy serialization of PDFs and encoding pages in parallel. When I started writing printpdf, I was new to Rust, so I didn't really know how to design a proper API. The goal is to be able to do text shaping, kerning, page layout, etc. outside of printpdf using a simple trait - some people prefer freetype, others rusttype, others harfbuzz - ideally printpdf should be able to accept all external font shapers, without me having to write extra code for each one.

> Keeping track of the current settings (colors, spacing, line height, etc.) to avoid redundant operations

That should be done outside of printpdf, however in the 2.0 API I am planning to do something like this, i.e. a simple function that optimizes the `pdf.page.operators` to reduce duplicates. I.e. `fn optimize_operators(input: Vec<Operator>) -> Vec<Operator>`.

> Transforming between the PDF coordinate system and the “logical” coordinate system (relative to the upper left corner)

Well my goal was to one day hook up printpdf to my other crate [azul](https://azul.rs/), in order to have a "PDF viewer / editor -> PDF generation" pipeline, so to have dedicated "layout engine" take care of coordinate system transformations. I wouldn't merge this into printpdf, because that's the job of the layout engine (in your case `genpdf`, in my case [`azul-layout`](https://docs.rs/azul-layout/0.0.4/azul_layout/)).

> Views on a sub-area of a layer

Not exactly sure what you mean by "views". I haven't read the PDF reference completely.

printpdf itself should just provide the basic implementation of the PDF reference, so that you can build more sophisticated tools on top.

**Comment by robinkrahl** [comment]
Okay, thanks for the detailed answer!

**Comment by robinkrahl** [comment]
I think you should update the readme to reflect this.  Currently, “Aligning / layouting text” is listed as a planned feature, and “Kerning is currently not done“ implies that it might be done in the future.
