### ISSUE TITLE
Status of the rusttype dependency

### ISSUE THREAD

**Issue by robinkrahl** [fschutt/printpdf#75]
`printpdf` currently uses `rusttype` 0.8 that is no longer maintained.  I experimented with updating `rusttype` to 0.9.  It seems to work fine, but I noticed that `ab_glyph` is `rusttype`’s more efficient successor (by the same author).  Then I noticed that `printpdf` doesn’t really need `rusttype` or `ab_glyph` because they mainly deal with font rendering and rasterization.  Instead it could directly use `ttf-parser`.

So my questions are:
- Is there a reason to stick with `rusttype` 0.8?
- If no, should `printpdf`
  - update to `rusttype` 0.9,
  - move to `ab_glyph` or
  - move to `ttf-parser`?

**Comment by fschutt** [comment]
> Is there a reason to stick with rusttype 0.8?

No, but see #28 - it's just that nobody has implemented it (yet) and upgrading to 0.9 was a bit difficult.

You could theoretically use ttf-parser, but that limits you to TTF fonts. I had originally hoped that rusttype would add support for OTF fonts. This hasn't happened.

If you want to work on the font system, just move all the functions that currently depend on rusttype into a trait first, so that the implementation (rusttype, allsorts, harfbuzz, freetype, ab_glyph, whatever) can be separate from the implementation.

Ideally I'd want something like `allsorts`, because it can parse **and shape** TTF, OTF, WOFF and other font formats and it's a pure-Rust library that is already being used in commercial products, so there is some money / maintainership behind it.

**Comment by robinkrahl** [comment]
Let’s start with moving the font access into a helper trait, okay?

Do you want to allow users to choose the font implementation at run time or compile time, or would that trait only be used by `printpdf` internally to make it easier to replace the implementation in the future?

**Comment by jrmuizel** [comment]
> > Is there a reason to stick with rusttype 0.8?
> 
> No, but see #28 - it's just that nobody has implemented it (yet) and upgrading to 0.9 was a bit difficult.
> 
> You could theoretically use ttf-parser, but that limits you to TTF fonts. I had originally hoped that rusttype would add support for OTF fonts. This hasn't happened.

ttf-parser supports OTF fonts. rusttype gained support with the switch to ttf-parser. 
```
The current capabilities of RustType:

    Reading OpenType formatted fonts and font collections. This includes *.ttf as well as *.otf font files.
```

**Comment by fschutt** [comment]
@robinkrahl Ideally at runtime with a `Box<Trait>` - printpdf isn't an extremely high-performance library, I don't think you have to count microseconds when writing a PDF and using a boxed trait makes it easier to compare two different font implementations - so that in the same PDF you can write one text with harfbuzz, the other text with ttf-parser and compare the results directly.

@jrmuizel Yes, but as far as I know, it is / was limited to OTF fonts that are just wrappers around TTF fonts (may be wrong). And while ttf-parser supports kerning (I think), it's not a full font shaper that you'd need for more complex scripts. But anyway, this is why I want the font implementation outside of printpdf, so that the decision on which implementation is better isn't up to me.

**Comment by robinkrahl** [comment]
Refactoring the font access is pretty straight-forward, see:
	https://github.com/robinkrahl/printpdf/tree/font-trait
The only problem is that we can’t clone a boxed trait object, so
ExternalFont could no longer implement Clone, cascading all the way down
to the PdfDocument.

Do you happen to have an idea how to solve this?  Otherwise I’ll take a
closer look later today or next week.

**Comment by fschutt** [comment]
I think it should work if the trait `FontData` requires `Clone`:

```rust
pub trait FontData: Debug + Clone {
    // ...
}
```

**Comment by robinkrahl** [comment]
That doesn’t work because it would require that FontData is Sized.  But
I have implemented a workaround and will open a PR soon!

**Comment by dzmitry-lahoda** [comment]
i have good calculation (more or less good) of multi line wrap for regular  normal fonts, still somewhat wrong for size, but mostly ok. but bold goes bad. may be something with rusttype and need to update.
