### ISSUE TITLE
donate button

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fschutt/printpdf#91]
i want to donate 20 usd, better in crypto

**Comment by fschutt** [comment]
Thanks! GitHub does not seem to support crypto addresses as valid funding links, which is why I can't add them to a funding.yml, but here are my addresses:

Bitcoin: 3DkYz32P77Bfv93wPgV66vs1vrUwgStcZU
Bitcoin Cash: 1QAi8xVB4nRtkaxTAXbzGHmg6nxuuezuYk
Ethereum: 0xb9960F9970b659056B03CB0241490aDA83A73CEa

Sorry for the late reply, but I needed to set up an account for receiving crypto.

**Comment by dzmitry-lahoda** [comment]
thanks, done.

**Comment by dzmitry-lahoda** [comment]
add these to readme

**Comment by dzmitry-lahoda** [comment]
or to profile

**Comment by fschutt** [comment]
Hm, I'm sorry to say it, but you probably sent it to the wrong address and the crypto might be lost. I've double-checked my addresses and they are correct:

![image](https://user-images.githubusercontent.com/12084016/108064648-46fa2480-705d-11eb-8ddf-a2d681e0bd31.png)

Either that or it just takes a while, but I've not received anything (yet?). I'm not that familiar with crypto, I just made a coinbase account and copied the "receive" address.

I'm just commenting to see if there's something wrong on my or your end (so that future transactions won't get lost again). Thank you for your donation anyway (even though it might have gotten lost), it's the thought that counts.

**Comment by dzmitry-lahoda** [comment]
fuck, sorry, yes. sent to wrong address, but it was mine. so here it is:
```
Withdrawal details:
Instrument: Crypto
Requested amount: ETH 0.02000000
Commission: ETH 0.01000000
Total to be sent: ETH 0.01000000
Destination wallet: 0xb9960f9970b659056b03cb0241490ada83a73cea
Transaction hash: 0x34e0f0860e2c384598eafbb73715a5c09dad925595c7f33b79263e6ee60e53d6
```

**Comment by dzmitry-lahoda** [comment]
it was 35USD on first try, but lost half of donation now....

**Comment by dzmitry-lahoda** [comment]
as of now this lib is unique in rust ecosystem afaik to render pdfs..

**Comment by fschutt** [comment]
Thanks, I received it!

![image](https://user-images.githubusercontent.com/12084016/109284206-e5d20e00-781f-11eb-9f4f-018af682dfa5.png)
