### ISSUE TITLE
Why does `save` mandate a `BufWriter`?

### ISSUE THREAD

**Issue by griff** [fschutt/printpdf#94]
In `save`:
https://github.com/fschutt/printpdf/blob/097defa25d5d5a14520498043a30979fe4af8bba/src/types/pdf_document.rs#L343

It doesn´t seem to actually need it to be a `BufWriter` since it just calls `save_to` in `lopdf` which takes a `Write`.

**Comment by fschutt** [comment]
It's supposed to prevent you from passing in a `File` handle because then Rust would write the PDF character-by-character, requiring a syscall for every single character. I once benchmarked this crate and saving the file took the largest amount of time, that's why `BufWriter` is required. 

Of course you could also use an `io::Cursor<Vec<u8>>` to write the file to memory first, then flush the memory to disk, but it's just to prevent the default (passing in a `File` handle directly).

**Comment by LetsMelon** [comment]
I think it would be better to change the signature to just accept `Write` and maybe add to the docs, that it's recommended to use a `BufWriter`.

**Comment by fschutt** [comment]
Removed the `BufWriter`, now there's just `save_to_bytes()` in the `0.8` API, which saves to a `Vec<u8>`.
